-- DB2 SQL 练习 2026
-- 根据上传的文件内容，实现各种SQL查询

-- A. 列出所有员工的姓氏(LAST_NAME)、员工ID(Employee_ID)和部门ID(DEPARTMENT_ID)
SELECT LAST_NAME, EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEES;

-- B. 列出所有员工的姓氏(LAST_NAME)、员工ID(Employee_ID)和部门ID(DEPARTMENT_ID)
-- (与A相同，可能是确认)
SELECT LAST_NAME, EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEES;

-- C. 列出部门ID >= 80 的员工的姓氏(LAST_NAME)和部门ID(DEPARTMENT_ID)
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID >= 80;

-- D. 按部门ID分组，显示部门ID和员工数量
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- E. 按部门ID分组，显示员工数量 >= 6 的部门ID和员工数量
SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >= 6;

-- F. 显示部门ID(DEPARTMENT_ID)和部门名称(DEPARTMENT_NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

-- G. 列出LAST_NAME和SALARY
SELECT LAST_NAME, SALARY
FROM EMPLOYEES;

-- H. 列出SALARY最高的员工的LAST_NAME和SALARY
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- I. 使用WHERE连接EMPLOYEES和DEPARTMENTS表，显示DEPARTMENT_ID, DEPARTMENT_NAME, LAST_NAME
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.LAST_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- J. 使用JOIN连接EMPLOYEES和DEPARTMENTS表，显示DEPARTMENT_ID, DEPARTMENT_NAME, LAST_NAME
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.LAST_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- K. 列出所有员工和部门，包括没有分配部门的员工
-- (假设有LEFT JOIN)
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- L. 对于没有分配部门的员工，显示他们的姓名
SELECT LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;